#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

import subprocess

units = ["elabftw.service", "elabftw-db.service", "elabftw-app.service"]
subprocess.run(["systemctl", "--user", "enable", *units], check=True)
subprocess.run(["systemctl", "--user", "restart", "elabftw.service"], check=True)
